# Generated by Django 4.2.6 on 2023-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_recruiteeuser_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
