# Generated by Django 4.2.6 on 2023-10-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0002_recruiteeuser_profile_description_and_more'),
        ('jobsApp', '0002_alter_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.recruiteeuser')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsApp.skill')),
            ],
            options={
                'unique_together': {('recruitee_user', 'skill')},
            },
        ),
    ]
