# Generated by Django 4.2.6 on 2023-10-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
