# Generated by Django 4.2.6 on 2023-10-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_unique_together'),
        ('companiesApp', '0002_company_cover_photo_company_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
    ]
