# Generated by Django 4.2.6 on 2024-03-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interviewsApp", "0003_usersanswer"),
        ("usersApp", "0004_alter_user_cover_photo_alter_user_profile_pic"),
        ("jobsApp", "0004_job_is_remote_job_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="default_cover_photo.jpeg",
                null=True,
                upload_to="cover_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="default_profile_pic.jpeg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acceptedForQuiz", models.BooleanField(blank=True, null=True)),
                ("accepted", models.BooleanField(blank=True, null=True)),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interviewsApp.interview",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobsApp.job"
                    ),
                ),
                (
                    "recruitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersApp.recruiteeuser",
                    ),
                ),
            ],
        ),
    ]
