# Generated by Django 4.2.6 on 2023-10-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0001_initial'),
        ('jobsApp', '0001_initial'),
        ('interviewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='company_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.companyuser'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsApp.job'),
        ),
        migrations.AddField(
            model_name='interview',
            name='recruitee_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.recruiteeuser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewsApp.question'),
        ),
    ]
