# Generated by Django 4.2.6 on 2023-10-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewsApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewsApp.answer')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewsApp.quizquestion')),
            ],
        ),
    ]
