# Generated by Django 4.2.6 on 2024-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviewsApp", "0003_usersanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
