# Generated by Django 4.2.6 on 2023-10-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'city')},
        ),
    ]
